// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKuLRl97s-UBrXQQBzWKAab2ha6-CtjYI',
    appId: '1:473460590616:web:474d73189bf2b96d739b6d',
    messagingSenderId: '473460590616',
    projectId: 'symmetry-challenge',
    authDomain: 'symmetry-challenge.firebaseapp.com',
    storageBucket: 'symmetry-challenge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjugdIrOlErc1G2rlxegfq3dfJ_ABpp4',
    appId: '1:473460590616:android:e12dc3b412e36ad8739b6d',
    messagingSenderId: '473460590616',
    projectId: 'symmetry-challenge',
    storageBucket: 'symmetry-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABaJxcIgEk_Aq5Hcw_0ItuNgK7PMesDmo',
    appId: '1:473460590616:ios:242081485b2fc8f2739b6d',
    messagingSenderId: '473460590616',
    projectId: 'symmetry-challenge',
    storageBucket: 'symmetry-challenge.firebasestorage.app',
    iosBundleId: 'com.example.newsAppCleanArchitecture',
  );

}